// State
export const SAVE_STATE = 'SAVE_STATE'
export const LOAD_STATE = 'LOAD_STATE'

// Time
export const TICK_TIME = 'TICK_TIME'
export const GET_TIME = 'GET_TIME'

// Grid
export const ADD_GRID_ITEM = 'ADD_GRID_ITEM'
export const REMOVE_GRID_ITEM = 'REMOVE_GRID_ITEM'
export const SAVE_GRID_LAYOUT = 'SAVE_GRID_LAYOUT'

// Starmaps
export const ADD_STARMAP = 'ADD_STARMAP'
export const REMOVE_STARMAP = 'REMOVE_STARMAP'
export const UPDATE_STARMAP = 'UPDATE_STARMAP'

// Systems
export const FETCH_SYSTEMS = 'FETCH_SYSTEMS'
export const FETCH_DISCOVERED_SYSTEMS = 'FETCH_DISCOVERED_SYSTEMS'
export const FETCH_SYSTEM_BODY = 'FETCH_SYSTEM_BODY'
export const FETCH_SYSTEM_BODIES = 'FETCH_SYSTEM_BODIES'
export const FETCH_SYSTEMS_BODIES = 'FETCH_SYSTEMS_BODIES'
export const FETCH_SYSTEMS_LIST = 'FETCH_SYSTEMS_LIST'
export const FETCH_SYSTEMS_WORMHOLES = 'FETCH_SYSTEMS_WORMHOLES'
export const FETCH_SYSTEM_SHIP = 'FETCH_SYSTEM_SHIP'
export const FETCH_SYSTEM = 'FETCH_SYSTEM'

// Races
export const FETCH_RACES = 'FETCH_RACES'
export const FETCH_RACE = 'FETCH_RACE'
export const SWITCH_RACE = 'SWITCH_RACE'

// Engine Design
export const FETCH_ENGINE_DESIGNS = 'FETCH_ENGINE_DESIGNS'
export const RESEARCH_ENGINE_DESIGNS = 'RESEARCH_ENGINE_DESIGNS'
export const FETCH_ENGINE_DESIGN = 'FETCH_ENGINE_DESIGN'
export const CREATE_ENGINE_DESIGN = 'CREATE_ENGINE_DESIGN'
export const DELETE_ENGINE_DESIGN = 'DELETE_ENGINE_DESIGN'

// Missle Launcher Design
export const FETCH_MISSLE_LAUNCHER_DESIGNS = 'FETCH_MISSLE_LAUNCHER_DESIGNS'
export const RESEARCH_MISSLE_LAUNCHER_DESIGNS = 'RESEARCH_MISSLE_LAUNCHER_DESIGNS'
export const FETCH_MISSLE_LAUNCHER_DESIGN = 'FETCH_MISSLE_LAUNCHER_DESIGN'
export const CREATE_MISSLE_LAUNCHER_DESIGN = 'CREATE_MISSLE_LAUNCHER_DESIGN'
export const DELETE_MISSLE_LAUNCHER_DESIGN = 'DELETE_MISSLE_LAUNCHER_DESIGN'

// Laser Design
export const FETCH_LASER_DESIGNS = 'FETCH_LASER_DESIGNS'
export const RESEARCH_LASER_DESIGNS = 'RESEARCH_LASER_DESIGNS'
export const FETCH_LASER_DESIGN = 'FETCH_LASER_DESIGN'
export const CREATE_LASER_DESIGN = 'CREATE_LASER_DESIGN'
export const DELETE_LASER_DESIGN = 'DELETE_LASER_DESIGN'

// Ship Design
export const FETCH_SHIP_DESIGNS = 'FETCH_SHIP_DESIGNS'
export const FETCH_SHIP_DESIGN = 'FETCH_SHIP_DESIGN'
export const CREATE_SHIP_DESIGN = 'CREATE_SHIP_DESIGN'
export const DELETE_SHIP_DESIGN = 'DELETE_SHIP_DESIGN'

// Ship
export const TOGGLE_SHIELDS = 'TOGGLE_SHIELDS'
export const CREATE_SHIP_ORDER = 'CREATE_SHIP_ORDER'
export const UPDATE_SHIP_ORDER = 'UPDATE_SHIP_ORDER'
export const DELETE_SHIP_ORDER = 'DELETE_SHIP_ORDER'
export const DELETE_SHIP_CONDITIONAL_ORDER = 'DELETE_SHIP_CONDITIONAL_ORDER'

// Research
export const FETCH_RESEARCH = 'FETCH_RESEARCH'
export const UNLOCK_ALL_RESEARCH = 'UNLOCK_ALL_RESEARCH'
export const FETCH_RACE_RESEARCH = 'FETCH_RACE_RESEARCH'
export const FETCH_ENGINE_DESIGN_FUEL_CONSUMPTIONS = 'FETCH_ENGINE_DESIGN_FUEL_CONSUMPTIONS'
export const RESEARCH_ENGINE_DESIGN_FUEL_CONSUMPTIONS = 'RESEARCH_ENGINE_DESIGN_FUEL_CONSUMPTIONS'
export const FETCH_ENGINE_DESIGN_MODIFIERS = 'FETCH_ENGINE_DESIGN_MODIFIERS'
export const RESEARCH_ENGINE_DESIGN_MODIFIERS = 'RESEARCH_ENGINE_DESIGN_MODIFIERS'
export const FETCH_ENGINE_DESIGN_SIZES = 'FETCH_ENGINE_DESIGN_SIZES'
export const RESEARCH_ENGINE_DESIGN_SIZES = 'RESEARCH_ENGINE_DESIGN_SIZES'
export const FETCH_ENGINE_DESIGN_TECHNOLOGIES = 'FETCH_ENGINE_DESIGN_TECHNOLOGIES'
export const RESEARCH_ENGINE_DESIGN_TECHNOLOGIES = 'RESEARCH_ENGINE_DESIGN_TECHNOLOGIES'
export const FETCH_MISSLE_LAUNCHER_DESIGN_SIZES = 'FETCH_MISSLE_LAUNCHER_DESIGN_SIZES'
export const RESEARCH_MISSLE_LAUNCHER_DESIGN_SIZES = 'RESEARCH_MISSLE_LAUNCHER_DESIGN_SIZES'
export const FETCH_MISSLE_LAUNCHER_DESIGN_RELOAD_RATES = 'FETCH_MISSLE_LAUNCHER_DESIGN_RELOAD_RATES'
export const RESEARCH_MISSLE_LAUNCHER_DESIGN_RELOAD_RATES = 'RESEARCH_MISSLE_LAUNCHER_DESIGN_RELOAD_RATES'
export const FETCH_MISSLE_LAUNCHER_DESIGN_REDUCED_SIZES = 'FETCH_MISSLE_LAUNCHER_DESIGN_REDUCED_SIZES'
export const RESEARCH_MISSLE_LAUNCHER_DESIGN_REDUCED_SIZES = 'RESEARCH_MISSLE_LAUNCHER_DESIGN_REDUCED_SIZES'
export const FETCH_LASER_DESIGN_FOCAL_SIZES = 'FETCH_LASER_DESIGN_FOCAL_SIZES'
export const RESEARCH_LASER_DESIGN_FOCAL_SIZES = 'RESEARCH_LASER_DESIGN_FOCAL_SIZES'
export const FETCH_LASER_DESIGN_WAVELENGTHS = 'FETCH_LASER_DESIGN_WAVELENGTHS'
export const RESEARCH_LASER_DESIGN_WAVELENGTHS = 'RESEARCH_LASER_DESIGN_WAVELENGTHS'
export const FETCH_LASER_DESIGN_RECHARGE_RATES = 'FETCH_LASER_DESIGN_RECHARGE_RATES'
export const RESEARCH_LASER_DESIGN_RECHARGE_RATES = 'RESEARCH_LASER_DESIGN_RECHARGE_RATES'
export const FETCH_LASER_DESIGN_REDUCED_SIZES = 'FETCH_LASER_DESIGN_REDUCED_SIZES'
export const RESEARCH_LASER_DESIGN_REDUCED_SIZES = 'RESEARCH_LASER_DESIGN_REDUCED_SIZES'
export const FETCH_ARMOR = 'FETCH_ARMOR'
export const RESEARCH_ARMOR = 'RESEARCH_ARMOR'
export const FETCH_SHIELD = 'FETCH_SHIELD'
export const RESEARCH_SHIELD = 'RESEARCH_SHIELD'
export const FETCH_FUEL_STORAGES = 'FETCH_FUEL_STORAGES'
export const RESEARCH_FUEL_STORAGES = 'RESEARCH_FUEL_STORAGES'
export const FETCH_CARGO_HANDLING_SYSTEMS = 'FETCH_CARGO_HANDLING_SYSTEMS'
export const RESEARCH_CARGO_HANDLING_SYSTEMS = 'RESEARCH_CARGO_HANDLING_SYSTEMS'
export const FETCH_CARGO_HOLDS = 'FETCH_CARGO_HOLDS'
export const RESEARCH_CARGO_HOLDS = 'RESEARCH_CARGO_HOLDS'
export const FETCH_JUMP_GATE_MODULES = 'FETCH_JUMP_GATE_MODULES'
export const RESEARCH_JUMP_GATES = 'RESEARCH_JUMP_GATES'
export const FETCH_MINES = 'FETCH_MINES'
export const RESEARCH_MINES = 'RESEARCH_MINES'
export const FETCH_RESEARCH_LABS = 'FETCH_RESEARCH_LABS'
export const RESEARCH_RESEARCH_LABS = 'RESEARCH_RESEARCH_LABS'
export const FETCH_FUEL_REFINERIES = 'FETCH_FUEL_REFINERIES'
export const RESEARCH_FUEL_REFINERIES = 'RESEARCH_FUEL_REFINERIES'
export const FETCH_CONSTRUCTION_FACTORIES = 'FETCH_CONSTRUCTION_FACTORIES'
export const RESEARCH_CONSTRUCTION_FACTORIES = 'RESEARCH_CONSTRUCTION_FACTORIES'
export const FETCH_MASS_DRIVERS = 'FETCH_MASS_DRIVERS'
export const RESEARCH_MASS_DRIVERS = 'RESEARCH_MASS_DRIVERS'
export const FETCH_GEOLOGICAL_SENSORS = 'FETCH_GEOLOGICAL_SENSORS'
export const RESEARCH_GEOLOGICAL_SENSORS = 'RESEARCH_GEOLOGICAL_SENSORS'
export const FETCH_GRAVITATIONAL_SENSORS = 'FETCH_GRAVITATIONAL_SENSORS'
export const RESEARCH_GRAVITATIONAL_SENSORS = 'RESEARCH_GRAVITATIONAL_SENSORS'

// Production
export const FETCH_PRODUCTION = 'FETCH_PRODUCTION'
export const UPDATE_PRODUCTION = 'UPDATE_PRODUCTION'

// Installments
export const FETCH_INSTALLMENTS = 'FETCH_INSTALLMENTS'
export const FETCH_BODY_INSTALLMENTS = 'FETCH_BODY_INSTALLMENTS'

// Mass Driver
export const UPDATE_MASS_DRIVER = 'UPDATE_MASS_DRIVER'

// Fuel Refineries
export const TOGGLE_FUEL_REFINERIES = 'TOGGLE_FUEL_REFINERIES'